#!groovy


pipeline{
    agent {
        docker {
            image 'continuumio/miniconda3:latest'
        }
    }

    parameters {
        string(defaultValue: '', description: 'Branch of the incubator-sdap-nexusproto project to build against. Leave blank to use version from pip specified in requirements (this does not currently work).', name: 'buildNexusprotoBranch')
    }

    stages{
        stage("Install nexusproto From Source"){
            when{
                expression { return params.buildNexusprotoBranch ==~ /SDAP-\d+/ }
            }
            steps{
                git branch: "${params.buildNexusprotoBranch}", credentialsId: 'fgreg-github', url: 'https://github.com/apache/incubator-sdap-nexusproto'
                sh './gradlew clean build pythonInstall'
            }
        }
        stage("Build"){
            steps{
                git branch: "${env.BRANCH_NAME}", credentialsId: 'fgreg-github', url: 'https://github.com/apache/incubator-sdap-ningesterpy'
                sh 'python setup.py sdist'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: 'dist/*.tar.gz', fingerprint: true, onlyIfSuccessful: true
        }
    }
}